language: generic

sudo: required

services:
  - docker

before-install:
  - docker build -t uad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true uad/docker-react npm run test

  